[[redirects]]
from = "/vce-shopify/*"
to = "https://vcelink.myshopify.com/:splat"
status = 200
force = true

[[redirects]]
from = "/radash-docs/*"
to = "https://radash-docs.vercel.app/:splat"
status = 200
force = true

[[redirects]]
from = "/amazon-images/*"
to = "https://m.media-amazon.com/images/:splat"
status = 200
force = true
